// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTNoGGGdo8cq95RUi9XJByhWgilkh_Xes',
    appId: '1:175726792836:web:c414d506982afd047132d1',
    messagingSenderId: '175726792836',
    projectId: 'tradeappadmin-3d4df',
    authDomain: 'tradeappadmin-3d4df.firebaseapp.com',
    storageBucket: 'tradeappadmin-3d4df.appspot.com',
    measurementId: 'G-1TBFVSXD0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGF0r9-oeoKnSJjM91KaqQR84IptQxLMw',
    appId: '1:175726792836:android:dcbb6a832b3c7da77132d1',
    messagingSenderId: '175726792836',
    projectId: 'tradeappadmin-3d4df',
    storageBucket: 'tradeappadmin-3d4df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4BSbGjdcNxptnQs3jqN1Tg98A4AD0xzw',
    appId: '1:175726792836:ios:45e37ea188eaa8d27132d1',
    messagingSenderId: '175726792836',
    projectId: 'tradeappadmin-3d4df',
    storageBucket: 'tradeappadmin-3d4df.appspot.com',
    iosBundleId: 'com.example.tradingWebAppAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4BSbGjdcNxptnQs3jqN1Tg98A4AD0xzw',
    appId: '1:175726792836:ios:45e37ea188eaa8d27132d1',
    messagingSenderId: '175726792836',
    projectId: 'tradeappadmin-3d4df',
    storageBucket: 'tradeappadmin-3d4df.appspot.com',
    iosBundleId: 'com.example.tradingWebAppAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTNoGGGdo8cq95RUi9XJByhWgilkh_Xes',
    appId: '1:175726792836:web:57d976e25c07f6407132d1',
    messagingSenderId: '175726792836',
    projectId: 'tradeappadmin-3d4df',
    authDomain: 'tradeappadmin-3d4df.firebaseapp.com',
    storageBucket: 'tradeappadmin-3d4df.appspot.com',
    measurementId: 'G-PDRLHKHFBP',
  );
}
